version: "3.3"

networks:
    zd-2d:
        driver: bridge

services:
    frontend:
        container_name: zd-2d-toolkit
        restart: always
        ports:
            - 3003:80
        networks:
            - zd-2d
        build:
            context: .
            dockerfile: Dockerfile.prod
