version: "3.3"

networks:
    zd-2d:
        driver: bridge

services:
    frontend:
        build: ./
        container_name: zd-2d-toolkit
        volumes:
            - ./src:/app/src
            - /node_modules
        ports:
            - 3003:3000
        stdin_open: true
        tty: true
        restart: always
        networks:
            - zd-2d
